name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: version
      run: |
        echo "::set-output name=version::v$(date +%Y%m%d_%H%M%S)"
        echo "{version2}={v$(date +%Y%m%d_%H%M%S)}" >> $GITHUB_OUTPUT
      id: version
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag plugin:latest
        docker create --name plugin plugin
        mkdir -p ./plugin
        docker cp plugin:/app/mosquitto_topic_jail_all.so ./plugin/
        docker cp plugin:/usr/bin/mosquitto_pub     ./plugin/
        docker cp plugin:/usr/bin/mosquitto_sub     ./plugin/
        docker cp plugin:/usr/lib/libmosquitto.so.1 ./plugin/
        docker cp plugin:/usr/bin/mosquitto         ./plugin/
        docker cp plugin:/usr/bin/mosquitto_passwd  ./plugin/
        docker cp plugin:/app/test.conf             ./plugin/
        docker cp plugin:/app/test.sh               ./plugin/

        docker rm plugin
        tar -czvf ./plugin/plugin.tar.gz -C ./plugin mosquitto_topic_jail_all.so mosquitto_pub mosquitto_sub \
        libmosquitto.so.1 mosquitto mosquitto_passwd

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name:  ${{ steps.version.outputs.version }}
        release_name: ${{ steps.version.outputs.version }}
        body: |
          Release notes for ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false

    - name: Save PR number
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      env:
        REL_NUMBER: ${{ steps.version.outputs.version }}
      run: |
        mkdir -p ./rel
        echo $REL_NUMBER > ./rel/rel_number
    - uses: actions/upload-artifact@v3
      with:
        name: rel_number
        path: rel/
    - name: Upload Release Asset
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./plugin/plugin.tar.gz
        asset_name: mosquitto_topic_jail.tar.gz
        asset_content_type: application/octet-stream
